### ISSUE TITLE
на oauth реализовать авторизацию через все социалки

### ISSUE THREAD

**Issue by shemerey** [saks/layouts#7]
одна кнопка войти (по ней мы выбираем социалку) кнопки зарегестрироваться нет 
попап с кнопками сокиалок (сверстать)

**Comment by shemerey** [comment]
есть проблемка в идентификации пользователя
- если пользователь заходит через разные социалки то мы считаем что это разный пользователь, можем остановиться на этом и не парится, и оставить вход только через социалки вообще без возможности самостоятельной регистрации (тут есть минус если падает социалка то мы остаемся без пользователя)
- в качестве уникального идентификатора через который мы можем связывать пользователя из разных источников служит email, проблема заключается в следующем: не все социалки предоставляют email  как часть пользовательской информации

есть два варианта 
- используем собственную регистрацию и те сервисы которые предоставляют email ползователя
- используем все сервисы после авторизации через те которые не предоставляют email перекидываем на страницу где спрашиваем email и в фоне отправляем письмо для подтверждения по подтверждению агрегируем аккаунты в один

**Comment by saks** [comment]
Думаю вариант где мы используем email из социалок если он отдаётся, а если нет - то просим его ввести и подтверждение - лучше :)

**Comment by shemerey** [comment]
угу, остается вопрос в что делаем если такой email уже сесть в базе

**Comment by saks** [comment]
в каком случае? при логине или при регистрации?

**Comment by shemerey** [comment]
в ситуации когда пользователь залогинился через фейс бук например или gmail и мы записали его мыло, а потом он залогинился через вконтакте и мы попросили его ввести мыло, он вводит а мыло уже есть в базе

я как вариант сделать так 
он воодит мыло, оно уже есть в базе, мы куда то его сохраняем и высылаем письмо с подтверждением, когда он подтверждает мы коннектим вконтакте с тем аккаунтом в котором это мыло уже было использовано 

остается вопрос как это красиво хранить и обробатывать, я так понимаю нужно делать доп табличку с провайдарами и связывать их с нашими пользователями 

но получается как то не прозрачно :-( и монструозненько 

можно конечно забить и считать что пользователь из facebook и пользователь из vkontakte это два разных пользователя

**Comment by saks** [comment]
думаю что забивать это точно плохая идея, т.к. потом мы к ним не привяжем их "избранное".
Хранить их можно прямо в документе пользователя, если по ним искать не нужно, если нужно:
- либо вынести в пользователя необходимые дополнительные поля(email, some_site_user_name, site_2_user_name)
- либо хранить их в другой коллекции и связывать по id
